database:
  url: jdbc:postgresql://${NAIS_DATABASE_FILLAGER_FILLAGER_HOST}:${NAIS_DATABASE_FILLAGER_FILLAGER_PORT}/${NAIS_DATABASE_FILLAGER_FILLAGER_DATABASE}
  username: ${NAIS_DATABASE_FILLAGER_FILLAGER_USERNAME}
  password: ${NAIS_DATABASE_FILLAGER_FILLAGER_PASSWORD}
